language: node_js
node_js:
  - 11.6.0
cache: npm


install: 
 - npm install

script:
  - docker pull gabrielsato1/XYZ
  - docker run -v $PWD/:/app/report/gabrielsato1/XYZ

after_script:
 - bash ./telegram_notification.sh 
  
